### ISSUE TITLE
Mac OS X El Capitan Kodi Isengard

### ISSUE THREAD

**Issue by aarifsumra** [YoColdRain/Hotstar-Rain#2]
I am getting following error

```
23:14:15 T:123145307209728  NOTICE: -->Python Interpreter Initialized<--
23:14:15 T:123145307209728   ERROR: /Users/aarif/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
23:14:15 T:123145307209728   ERROR: /Users/aarif/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
23:14:16 T:123145307209728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/Users/aarif/Library/Application Support/Kodi/addons/plugin.video.hotstar-rain/default.py", line 478, in <module>
                                                get_video_url()
                                              File "/Users/aarif/Library/Application Support/Kodi/addons/plugin.video.hotstar-rain/default.py", line 350, in get_video_url
                                                raw3_start = videos[0][1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
23:14:16 T:140735252115456   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.hotstar-rain/?mode=9&name=%5BB%5D%5BCOLOR+orange%5DPrem+Ratan+Dhan+Payo%5B%2FCOLOR%5D%5B%2FB%5D&url=http%3A%2F%2Fgetcdn.hotstar.com%2FAVS%2Fbesc%3Faction%3DGetCDN%26asJson%3DY%26channel%3DPCTV%26type%3DVOD%26id%3D1000084315&image=http%3A%2F%2Fmedia0-starag.startv.in%2Fr1%2Fthumbs%2FPCTV%2F15%2F1000084315%2FPCTV-1000084315-vl.jpg]
```

**Comment by YoColdRain** [comment]
hi, please leave issues in original forum thread, not under github.  There is answer for this fix on last page of the forum, until I can get new release out.
